export const POINTS_REWARDS = {
    SESSION_COMPLETED: 10,
    SESSION_RATED_5_STARS: 5,
    SESSION_RATED_4_STARS: 3,
    SESSION_RATED_3_STARS: 1,
    PROFILE_COMPLETED: 20,
    FIRST_SESSION: 15,
    FEEDBACK_GIVEN: 2,
    SWAP_REQUEST_SENT: 1,
    SWAP_REQUEST_ACCEPTED: 5,
    SKILL_ADDED: 3,
    CONSECUTIVE_DAY_BONUS: 5,
    HELP_COMMUNITY_MEMBER: 2,
} as const

export const LEADERBOARD_CONFIG = {
    DEFAULT_PAGE_SIZE: 10,
    MAX_PAGE_SIZE: 50,
    CACHE_DURATION: 5 * 60 * 1000,
} as const

export const POINTS_CONFIG = {
    MIN_POINTS: 0,
    MAX_POINTS_PER_ACTION: 100,
    NEGATIVE_POINTS_ALLOWED: false,
} as const
